# Regresión OLS Práctica
Katlyn Goeujon-Mackness <br>
31/31/2025 <br>
**Descripción:** Un espacio para practicar el método OLS de regresión lineal.

## Estructura
### Intervalos de confianza en regresión
* Descubrir cómo calcular pronósticos puntuales y sus intervalos de confianza en el contexto de la regresión lineal múltiple. 
* Utilizar la distribución T de Student y la desviación estándar de la regresión para evaluar la incertidumbre en las predicciones del modelo.

### Análisis de series de tiempo
* Identificar patrones y tendencias en datos temporales.
* Explorar técnicas para modelar y predecir comportamientos futuros basados en datos históricos.


## Intervalos de confianza

In [1]:
# Importar librerías
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

Nota: Para este ejemplo asumirermos que los datos de entrenamiento son iguales a los datos de prueba.

In [2]:
Y = np.array([[3], [1], [8], [3], [5]])
Y

array([[3],
       [1],
       [8],
       [3],
       [5]])

In [3]:
X = np.array([[1,3], [1,1], [1,5], [1,2], [1,4]])
X

array([[1, 3],
       [1, 1],
       [1, 5],
       [1, 2],
       [1, 4]])

In [4]:
XT_X = np.matmul(np.matrix.transpose(X), X)
XT_X

array([[ 5, 15],
       [15, 55]])

In [5]:
XT_X_inv = np.linalg.inv(XT_X)
XT_X_inv

array([[ 1.1, -0.3],
       [-0.3,  0.1]])

In [23]:
XT_Y = np.matmul(np.matrix.transpose(X), Y)
XT_Y

array([[20],
       [76]])

In [24]:
betas = np.matmul(XT_X_inv, XT_Y)
betas

array([[-0.8],
       [ 1.6]])

In [25]:
Y_pred = np.matmul(X, betas)
Y_pred

array([[4. ],
       [0.8],
       [7.2],
       [2.4],
       [5.6]])

In [26]:
Resid = Y - Y_pred
Resid

array([[-1. ],
       [ 0.2],
       [ 0.8],
       [ 0.6],
       [-0.6]])

In [27]:
# Cálculo de TSS (Suma total de cuadrados)
TSS = np.matmul(np.matrix.transpose(Y), Y) - len(Y) * (Y.mean()**2)
TSS


array([[28.]])

In [28]:
# Cálculo de ESS (Suma explicada de cuadrados)
ESS = np.matmul(np.matmul(np.matrix.transpose(betas), np.matrix.transpose(X)), np.matmul(X, betas)) - len(Y)*(Y.mean()**2)
ESS

array([[25.6]])

In [29]:
# Cálculo de RSS (Residuales al cuadrado)
RSS = TSS - ESS
RSS

array([[2.4]])

In [30]:
# Cálculo del Coeficiente de Determinación R Cuadrada
RSq = float(1 - RSS / TSS)
RSq

0.9142857142857201

In [31]:
# Calcular la varianze del error
s_cuad = RSS/(len(Y) - X.shape[1])
s_cuad

array([[0.8]])

In [32]:
# Cálculo del Coeficiente de Determinación R Cuadrada Ajustada
RSqAj = 1 - (RSS / (X.shape[0] - X.shape[1])) / (TSS / (X.shape[0] - 1))
RSqAj

array([[0.88571429]])

In [33]:
# Desviación estándar del error
import math

s = math.sqrt(s_cuad)
s

0.8944271909998852

In [35]:
# Obtención del valor crítico de la t de Student
import scipy.stats

#Grados de libertad: n - (k+1)
grados_libertad = len(Y) - X.shape[1]
Confianza = 0.95
q = (1-Confianza) / 2
t_critico = abs(scipy.stats.t.ppf(q, df=grados_libertad))
t_critico

np.float64(3.182446305284263)

In [36]:
# Vector de valores particulares de X
f = np.array([[1], [7]])
f

array([[1],
       [7]])

In [37]:
Margen_error = t_critico * (s * (float(np.matmul(np.matmul(np.matrix.transpose(f), XT_X_inv),f)) ** 0.5))
Margen_error

np.float64(3.8189355663409854)

In [38]:
Pron_puntual = float(np.matmul(np.matrix.transpose(f), betas))
Pron_puntual

10.400000000000006

In [39]:
# Límites del intervalo de confianze
Lim_inferior = Pron_puntual - Margen_error
Lim_superior = Pron_puntual + Margen_error
print("Intervalo de confianza: (", Lim_inferior, ",", Lim_superior, ")")

Intervalo de confianza: ( 6.58106443365902 , 14.218935566340992 )
